"""add models

Revision ID: 3eb536d940cc
Revises: 
Create Date: 2024-11-05 18:51:05.712170

"""
from werkzeug.security import generate_password_hash
from models import User
from app import db

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb536d940cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    existing_user = User.query.filter_by(username='admin').first()

    if not existing_user:
        admin_user = User(
            username='Matias',
            password_hash=generate_password_hash('1234'),
            is_admin=True,
        )
        db.session.add(admin_user)
        db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
