"""agrega el modelo Accesorio

Revision ID: d534888377ee
Revises: fffffdaa4b51
Create Date: 2024-11-08 00:35:40.179505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd534888377ee'
down_revision = 'fffffdaa4b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesorio')
    # ### end Alembic commands ###
