"""Eliminar columna modelo de Marca

Revision ID: e0747854e547
Revises: d534888377ee
Create Date: 2024-11-08 17:26:29.023296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0747854e547'
down_revision = 'd534888377ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('modelo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
